/**
 * 景点模块 mock 数据（P0–P3 前端 mock 驱动）。
 *
 * 对齐真实后端 wanderchina：
 * - CITIES_MOCK：11 城，slug/spotCount 与后端 cities 一致。
 * - SPOTS_MOCK：24 景点，slug/name/city/category/tags/rating/featured/hiddenGem/
 *   coverImage/gallery/summary/description 均取自后端真实数据；后端 view_count 全为 0，
 *   由 mock 给出合理热度分布（仅 viewCount 为合成值，其余字段与后端一致）。
 */
import type { City, Spot, RelatedPost } from "./types";

// 对齐真实后端 wanderchina.cities（11 城，slug 与后端一致；spotCount 取自后端景点计数）。
export const CITIES_MOCK: City[] = [
  {
    slug: "beijing",
    nameZh: "北京",
    name: "Beijing",
    coverImage: "https://picsum.photos/seed/beijing/800/600",
    description: "Imperial palaces, the Great Wall and hutong alley life.",
    bestSeason: "Sep–Oct · Apr–May",
    spotCount: 3,
  },
  {
    slug: "shanghai",
    nameZh: "上海",
    name: "Shanghai",
    coverImage: "https://picsum.photos/seed/shanghai/800/600",
    description: "Art-deco skyline meets lane-house nostalgia.",
    bestSeason: "Mar–May · Sep–Nov",
    spotCount: 3,
  },
  {
    slug: "xi-an",
    nameZh: "西安",
    name: "Xi'an",
    coverImage: "https://picsum.photos/seed/xian/800/600",
    description: "Terracotta warriors and the starting point of the Silk Road.",
    bestSeason: "Mar–May · Sep–Oct",
    spotCount: 2,
  },
  {
    slug: "chengdu",
    nameZh: "成都",
    name: "Chengdu",
    coverImage: "https://picsum.photos/seed/chengdu/800/600",
    description: "Pandas, peppery hotpot and laid-back street life.",
    bestSeason: "Mar–Jun · Sep–Nov",
    spotCount: 2,
  },
  {
    slug: "hangzhou",
    nameZh: "杭州",
    name: "Hangzhou",
    coverImage: "https://picsum.photos/seed/hangzhou/800/600",
    description: "West Lake, ancient temples and slow tea-house living.",
    bestSeason: "Mar–May · Sep–Nov",
    spotCount: 2,
  },
  {
    slug: "guilin",
    nameZh: "桂林",
    name: "Guilin",
    coverImage: "https://picsum.photos/seed/guilin/800/600",
    description: "Karst peaks reflected in the dreamy Li River.",
    bestSeason: "Apr–Oct",
    spotCount: 2,
  },
  {
    slug: "lhasa",
    nameZh: "拉萨",
    name: "Lhasa",
    coverImage: "https://picsum.photos/seed/lhasa/800/600",
    description: "Potala Palace and the high plateau's spiritual heart.",
    bestSeason: "May–Oct",
    spotCount: 2,
  },
  {
    slug: "lijiang",
    nameZh: "丽江",
    name: "Lijiang",
    coverImage: "https://picsum.photos/seed/lijiang/800/600",
    description: "Naxi old town beneath the Jade Dragon Snow Mountain.",
    bestSeason: "Mar–May · Sep–Nov",
    spotCount: 2,
  },
  {
    slug: "guangzhou",
    nameZh: "广州",
    name: "Guangzhou",
    coverImage: "https://picsum.photos/seed/guangzhou/800/600",
    description: "Cantonese dim sum, colonial architecture and a humid skyline.",
    bestSeason: "Oct–Dec · Feb–Apr",
    spotCount: 2,
  },
  {
    slug: "chongqing",
    nameZh: "重庆",
    name: "Chongqing",
    coverImage: "https://picsum.photos/seed/chongqing/800/600",
    description: "Mountain city of hotpot, night views and Yangtze confluence.",
    bestSeason: "Mar–May · Sep–Nov",
    spotCount: 2,
  },
  {
    slug: "fuzhou",
    nameZh: "福州",
    name: "Fuzhou",
    coverImage: "https://picsum.photos/seed/fuzhou/800/600",
    description: "Three lanes and seven alleys beside a quiet civic lake.",
    bestSeason: "Oct–Apr",
    spotCount: 2,
  },
];

export const SPOTS_MOCK: Spot[] = [
  {
    slug: "guilin-reed-flute-cave",
    nameZh: "芦笛岩",
    nameEn: "Reed Flute Cave",
    citySlug: "guilin",
    category: "nature",
    tags: ["Photo", "Family"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/guilin-reed-flute-cave/1200/800",
    gallery: ["https://picsum.photos/seed/guilin-reed-flute-cave-gallery/1200/800"],
    summaryEn: "A limestone cave of glittering stalactites and stalagmites, lit in rainbow colours.",
    summaryZh: "遍布钟乳石与石笋的溶洞，在彩色灯光下晶莹剔透，被誉为「大自然的艺术之宫」。",
    descriptionEn: "The forty-minute guided walk is conveniently close to the city centre and shows off the cave's best-lit chambers.",
    descriptionZh: "溶洞位于市中心不远，讲解游览约四十分钟，尽览最精美的石室。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 4700,
    postCount: 0,
    rating: 4.3,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "chongqing-ciqikou-ancient-town",
    nameZh: "磁器口古镇",
    nameEn: "Ciqikou Ancient Town",
    citySlug: "chongqing",
    category: "history",
    tags: ["Old Town", "Food", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/chongqing-ciqikou-ancient-town/1200/800",
    gallery: ["https://picsum.photos/seed/chongqing-ciqikou-ancient-town-gallery/1200/800"],
    summaryEn: "A restored Ming-Qing riverside town of teahouses, calligraphy shops and chilli-laden snack stalls.",
    summaryZh: "嘉陵江畔修复的明清古镇，茶馆、书法铺与辣味小吃摊沿石板路铺开。",
    descriptionEn: "Come for the morning teahouse scene and fresh maohuaxuewang hotpot, and climb to the old wharf for river views.",
    descriptionZh: "早茶时段最有味道，试试现做毛血旺，再登上老码头看江景。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 3900,
    postCount: 0,
    rating: 4.2,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "fuzhou-west-lake",
    nameZh: "福州西湖",
    nameEn: "West Lake",
    citySlug: "fuzhou",
    category: "nature",
    tags: ["Free", "Photo", "Family"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/fuzhou-west-lake/1200/800",
    gallery: ["https://picsum.photos/seed/fuzhou-west-lake-gallery/1200/800"],
    summaryEn: "A compact lakeside park in the city centre, quieter and more local than its famous Hangzhou namesake.",
    summaryZh: "市中心的小巧湖景公园，比杭州同名西湖更小、更安静，也更有本地生活气息。",
    descriptionEn: "Fuzhou's West Lake is a neighbourhood retreat where locals stroll, practise tai chi and boat under willow trees — a useful reminder that West Lake is a name, not a single place.",
    descriptionZh: "福州西湖是街坊邻里的休憩之地，本地人在此散步、打太极、垂柳下泛舟——它也提醒着旅行者：西湖是一个名字，而非独指一处。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 3500,
    postCount: 0,
    rating: 4.1,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "lijiang-lijiang-old-town",
    nameZh: "丽江古城",
    nameEn: "Lijiang Old Town",
    citySlug: "lijiang",
    category: "history",
    tags: ["UNESCO", "Old Town", "Night View", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/lijiang-lijiang-old-town/1200/800",
    gallery: ["https://picsum.photos/seed/lijiang-lijiang-old-town-gallery/1200/800"],
    summaryEn: "A UNESCO-listed maze of cobbled lanes, canals and Naxi timber houses beneath Jade Dragon Mountain.",
    summaryZh: "世界文化遗产，玉龙雪山下的纳西木构老城，青石板路与水渠纵横。",
    descriptionEn: "Wander off Sifang Street after dark, when lantern-lit lanes are quieter and the mountain looms at the lane's end.",
    descriptionZh: "入夜后离开四方街主路，灯笼照亮的巷弄格外清静，尽头是巍峨的雪山。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 7600,
    postCount: 0,
    rating: 4.6,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "guilin-li-river",
    nameZh: "漓江",
    nameEn: "Li River",
    citySlug: "guilin",
    category: "nature",
    tags: ["UNESCO", "Must-see", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/guilin-li-river/1200/800",
    gallery: ["https://picsum.photos/seed/guilin-li-river-gallery/1200/800"],
    summaryEn: "The classic karst cruise from Guilin to Yangshuo — sheer limestone peaks mirrored in calm green water.",
    summaryZh: "从桂林到阳朔的经典喀斯特水路，石灰岩峰林倒映在碧绿江水中。",
    descriptionEn: "Take the four-hour bamboo-raft or cruise option from Zhujiang Pier, passing the scenes printed on the ¥20 note.",
    descriptionZh: "可选择竹筏或游船，从竹江码头出发的四个多小时航程会经过印在二十元人民币背面的风景。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 9100,
    postCount: 0,
    rating: 4.7,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "hangzhou-lingyin-temple",
    nameZh: "灵隐寺",
    nameEn: "Lingyin Temple",
    citySlug: "hangzhou",
    category: "history",
    tags: ["Temple", "Hiking", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/hangzhou-lingyin-temple/1200/800",
    gallery: ["https://picsum.photos/seed/hangzhou-lingyin-temple-gallery/1200/800"],
    summaryEn: "One of China's great Buddhist monasteries, tucked into wooded hills west of West Lake.",
    summaryZh: "中国著名古刹之一，深藏于西湖以西的密林群山之间。",
    descriptionEn: "Arrive early to explore the mossy grottoes of Feilai Feng before the tour groups fill the courtyards.",
    descriptionZh: "建议赶早，赶在旅行团涌入前细看飞来峰的摩崖石刻。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 6000,
    postCount: 0,
    rating: 4.7,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "chengdu-chengdu-panda-base",
    nameZh: "大熊猫繁育研究基地",
    nameEn: "Chengdu Panda Base",
    citySlug: "chengdu",
    category: "nature",
    tags: ["Family", "Must-see", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/chengdu-chengdu-panda-base/1200/800",
    gallery: ["https://picsum.photos/seed/chengdu-chengdu-panda-base-gallery/1200/800"],
    summaryEn: "The best place on Earth to see giant pandas — cubs, bamboo-munching adults and red pandas in leafy enclosures.",
    summaryZh: "全球观赏大熊猫的最佳去处，茂密竹林中栖息着幼崽、成年熊猫与小熊猫。",
    descriptionEn: "Arrive at opening time to catch the pandas at their most active, then watch cubs climb trees in the nursery.",
    descriptionZh: "建议开门即入园，趁熊猫最精神的时候看它们进食，再到产房看幼崽爬树。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 11200,
    postCount: 0,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "hangzhou-west-lake",
    nameZh: "西湖",
    nameEn: "West Lake",
    citySlug: "hangzhou",
    category: "nature",
    tags: ["UNESCO", "Must-see", "Free", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/hangzhou-west-lake/1200/800",
    gallery: ["https://picsum.photos/seed/hangzhou-west-lake-gallery/1200/800"],
    summaryEn: "A UNESCO-listed lake of causeways, pagodas and willows that has inspired poets for over a millennium.",
    summaryZh: "世界文化遗产，苏堤白堤、亭台佛塔与垂柳相映，千年来一直是诗画江南的代名词。",
    descriptionEn: "Rent a shared bike for the Su Causeway, take a boat to the island of Three Pools, then watch the sunset by Leifeng Pagoda.",
    descriptionZh: "可租共享单车骑行苏堤，乘船登三潭印月小岛，再到雷峰塔边看日落。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 12000,
    postCount: 0,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "lhasa-jokhang-temple",
    nameZh: "大昭寺",
    nameEn: "Jokhang Temple",
    citySlug: "lhasa",
    category: "culture",
    tags: ["UNESCO", "Temple", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/lhasa-jokhang-temple/1200/800",
    gallery: ["https://picsum.photos/seed/lhasa-jokhang-temple-gallery/1200/800"],
    summaryEn: "Tibet's holiest shrine, whose rooftop views over Barkhor pilgrims make it Lhasa's spiritual heart.",
    summaryZh: "藏传佛教最神圣的殿堂，登顶可望见八廓街上转经的人潮，是拉萨的精神中心。",
    descriptionEn: "Join the clockwise kora around the Barkhor circuit after visiting the temple's golden-roofed chapels.",
    descriptionZh: "礼佛后沿八廓街顺时针转经一圈，感受朝圣者的日常。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 6800,
    postCount: 0,
    rating: 4.6,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "xi-an-terracotta-army",
    nameZh: "兵马俑",
    nameEn: "Terracotta Army",
    citySlug: "xi-an",
    category: "history",
    tags: ["UNESCO", "Must-see", "Museum"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/xi-an-terracotta-army/1200/800",
    gallery: ["https://picsum.photos/seed/xi-an-terracotta-army-gallery/1200/800"],
    summaryEn: "Thousands of life-size clay soldiers guard the tomb of the First Emperor, discovered in 1974.",
    summaryZh: "1974 年出土的秦始皇陵陪葬坑，数千个真人大小的陶俑军阵气势撼人。",
    descriptionEn: "Visit Pit 1 first for the famous rows of warriors, then the smaller pits for kneeling archers and bronze chariots.",
    descriptionZh: "先看一号坑的庞大军阵，再走二号、三号坑欣赏跪射俑与铜车马。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 13400,
    postCount: 0,
    rating: 4.9,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "beijing-great-wall-at-mutianyu",
    nameZh: "慕田峪长城",
    nameEn: "Great Wall at Mutianyu",
    citySlug: "beijing",
    category: "nature",
    tags: ["UNESCO", "Must-see", "Hiking", "Cable Car"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/beijing-great-wall-at-mutianyu/1200/800",
    gallery: ["https://picsum.photos/seed/beijing-great-wall-at-mutianyu-gallery/1200/800"],
    summaryEn: "A beautifully restored section of the Great Wall snaking over forested ridges north of the city.",
    summaryZh: "长城保存最完好、风景最秀美的段落之一，沿城北苍翠山脊蜿蜒起伏。",
    descriptionEn: "Cable cars, a chairlift and a toboggan run make Mutianyu the most family-friendly Great Wall section — far less crowded than Badaling.",
    descriptionZh: "缆车、索道与滑道一应俱全，是长城各段中亲子体验最友好的一处，客流也远少于八达岭。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 10500,
    postCount: 0,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "shanghai-the-bund",
    nameZh: "外滩",
    nameEn: "The Bund",
    citySlug: "shanghai",
    category: "district",
    tags: ["Must-see", "Night View", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/shanghai-the-bund/1200/800",
    gallery: ["https://picsum.photos/seed/shanghai-the-bund-gallery/1200/800"],
    summaryEn: "Shanghai's riverside promenade lined with grand colonial buildings, facing the Pudong towers across the Huangpu.",
    summaryZh: "黄浦江畔的滨江大道，一侧是恢弘的万国建筑博览群，隔江正对陆家嘴摩天楼群。",
    descriptionEn: "Best at dusk: the colonial facades light up as Pudong's skyline flickers on opposite the river.",
    descriptionZh: "黄昏时分最佳——万国建筑亮起灯光，对岸陆家嘴的天际线随之点亮。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 9800,
    postCount: 0,
    rating: 4.7,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "lhasa-potala-palace",
    nameZh: "布达拉宫",
    nameEn: "Potala Palace",
    citySlug: "lhasa",
    category: "history",
    tags: ["UNESCO", "Must-see", "Museum", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/lhasa-potala-palace/1200/800",
    gallery: ["https://picsum.photos/seed/lhasa-potala-palace-gallery/1200/800"],
    summaryEn: "The iconic thirteen-storey winter palace of the Dalai Lamas, rising red and white above Lhasa.",
    summaryZh: "达赖喇嘛的冬宫，红白相间的十三层宫堡雄踞红山之巅，是拉萨的永恒地标。",
    descriptionEn: "Acclimatise for a day before climbing the hundreds of steps; book tickets early as daily numbers are capped.",
    descriptionZh: "初到高原先适应一天再登数百级台阶；旺季门票数量有限，务必提前预订。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 8700,
    postCount: 0,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "beijing-temple-of-heaven",
    nameZh: "天坛",
    nameEn: "Temple of Heaven",
    citySlug: "beijing",
    category: "history",
    tags: ["UNESCO", "Temple", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/beijing-temple-of-heaven/1200/800",
    gallery: ["https://picsum.photos/seed/beijing-temple-of-heaven-gallery/1200/800"],
    summaryEn: "Where Ming and Qing emperors prayed for good harvests — famous for its circular Hall of Prayer.",
    summaryZh: "明清帝王祭天祈谷之所，以圆形祈年殿闻名于世。",
    descriptionEn: "The park is a local morning ritual too: you will meet tai chi groups, singers and dancers in the cypress groves.",
    descriptionZh: "天坛公园也是老北京晨练的舞台，柏树林里常有太极、合唱与舞蹈人群。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 7200,
    postCount: 0,
    rating: 4.6,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "guangzhou-chen-clan-ancestral-hall",
    nameZh: "陈家祠",
    nameEn: "Chen Clan Ancestral Hall",
    citySlug: "guangzhou",
    category: "culture",
    tags: ["Museum", "Photo", "Old Town"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/guangzhou-chen-clan-ancestral-hall/1200/800",
    gallery: ["https://picsum.photos/seed/guangzhou-chen-clan-ancestral-hall-gallery/1200/800"],
    summaryEn: "A dazzling Qing-dynasty clan hall covered in ridge figurines, carvings and painted ceramics.",
    summaryZh: "清代宗祠建筑的登峰造极之作，屋脊陶塑、木雕与彩绘琳琅满目。",
    descriptionEn: "One of the finest examples of Lingnan decorative art — allow an hour and look up at the rooftop figures.",
    descriptionZh: "岭南装饰艺术的集大成者——留一小时细品，别忘了抬头看屋脊上的陶塑。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 4300,
    postCount: 0,
    rating: 4.4,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "fuzhou-three-lanes-and-seven-alleys",
    nameZh: "三坊七巷",
    nameEn: "Three Lanes and Seven Alleys",
    citySlug: "fuzhou",
    category: "history",
    tags: ["Old Town", "Food", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/fuzhou-three-lanes-and-seven-alleys/1200/800",
    gallery: ["https://picsum.photos/seed/fuzhou-three-lanes-and-seven-alleys-gallery/1200/800"],
    summaryEn: "A preserved Ming-Qing quarter of narrow lanes and courtyard houses, once home to scholars and officials.",
    summaryZh: "保存完好的明清坊巷街区，窄巷深宅，曾是文人官宦的聚居之地。",
    descriptionEn: "Three Lanes and Seven Alleys is the best-surviving old quarter in Fuzhou: restored courtyard mansions, bookshops and snack stalls woven into a walkable grid.",
    descriptionZh: "三坊七巷是福州保存最完整的老城区：修葺一新的深宅大院、书店与小吃摊交织在可步行的坊巷格局中。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 4100,
    postCount: 0,
    rating: 4.3,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "beijing-forbidden-city",
    nameZh: "故宫",
    nameEn: "Forbidden City",
    citySlug: "beijing",
    category: "history",
    tags: ["UNESCO", "Must-see", "Museum"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/beijing-forbidden-city/1200/800",
    gallery: ["https://picsum.photos/seed/beijing-forbidden-city-gallery/1200/800"],
    summaryEn: "The imperial palace of the Ming and Qing dynasties, a vast complex of halls and courtyards at the heart of Beijing.",
    summaryZh: "明清两代的皇宫，由无数殿宇与庭院构成的庞大建筑群，坐镇北京中轴线的中心。",
    descriptionEn: "Walk north from Tiananmen through five ceremonial gates and ninety-something halls to feel the scale of imperial China. Allow at least half a day, and book tickets in advance.",
    descriptionZh: "从天安门向北穿过五重宫门与近百座殿宇，方能感受帝制中国的规模。建议预留至少半天，并提前预约门票。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 15200,
    postCount: 0,
    rating: 4.9,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "shanghai-yu-garden",
    nameZh: "豫园",
    nameEn: "Yu Garden",
    citySlug: "shanghai",
    category: "history",
    tags: ["Old Town", "Photo", "Food"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/shanghai-yu-garden/1200/800",
    gallery: ["https://picsum.photos/seed/shanghai-yu-garden-gallery/1200/800"],
    summaryEn: "A Ming-dynasty classical garden of rockeries, ponds and pavilions hidden behind the old city bazaar.",
    summaryZh: "藏身老城厢市集深处的明代古典园林，以假山、池沼与亭台取胜。",
    descriptionEn: "After the garden, wander the surrounding Yu Garden Bazaar for snacks like xiaolongbao and tanghulu.",
    descriptionZh: "游园后可逛毗邻的豫园商城，尝一尝小笼包、糖葫芦等地道小吃。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 5400,
    postCount: 0,
    rating: 4.4,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "lijiang-jade-dragon-snow-mountain",
    nameZh: "玉龙雪山",
    nameEn: "Jade Dragon Snow Mountain",
    citySlug: "lijiang",
    category: "nature",
    tags: ["Cable Car", "Hiking", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/lijiang-jade-dragon-snow-mountain/1200/800",
    gallery: ["https://picsum.photos/seed/lijiang-jade-dragon-snow-mountain-gallery/1200/800"],
    summaryEn: "A glacier-topped range of thirteen peaks, reached by cable car to meadows above 4,000 m.",
    summaryZh: "十三峰连绵的雪山，可乘索道登上海拔四千多米的草甸与冰川。",
    descriptionEn: "Book the big cable car ahead and carry oxygen — the summit walkway sits above 4,500 metres.",
    descriptionZh: "大索道需提前预约并自备氧气瓶，山顶栈道海拔超过 4500 米。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 6500,
    postCount: 0,
    rating: 4.5,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "shanghai-shanghai-museum-east",
    nameZh: "上海博物馆东馆",
    nameEn: "Shanghai Museum East",
    citySlug: "shanghai",
    category: "culture",
    tags: ["Museum", "Free", "Must-see"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/shanghai-shanghai-museum-east/1200/800",
    gallery: ["https://picsum.photos/seed/shanghai-shanghai-museum-east-gallery/1200/800"],
    summaryEn: "A new landmark museum on the Pudong waterfront showcasing China's finest bronzes and calligraphy.",
    summaryZh: "坐落浦东滨江的新地标博物馆，以顶级青铜器与中国书画收藏著称。",
    descriptionEn: "Free timed-entry galleries make it easy to dip into 5,000 years of Chinese art between skyline walks.",
    descriptionZh: "免费预约入馆，看展之余沿滨江步道赏天际线，动静皆宜。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 6200,
    postCount: 0,
    rating: 4.6,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "chengdu-wuhou-shrine",
    nameZh: "武侯祠",
    nameEn: "Wuhou Shrine",
    citySlug: "chengdu",
    category: "history",
    tags: ["Temple", "Old Town", "Food"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/chengdu-wuhou-shrine/1200/800",
    gallery: ["https://picsum.photos/seed/chengdu-wuhou-shrine-gallery/1200/800"],
    summaryEn: "A serene temple-museum honouring the strategist Zhuge Liang, set beside the lively Jinli bazaar.",
    summaryZh: "纪念诸葛亮的名胜，殿宇肃穆，毗邻热闹的锦里古街。",
    descriptionEn: "Combine the shrine with the adjacent Jinli Old Street for Sichuan snacks and folk crafts.",
    descriptionZh: "可把武侯祠与一墙之隔的锦里老街连成一线，吃川味小吃、逛民间手艺。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 4800,
    postCount: 0,
    rating: 4.5,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "guangzhou-canton-tower",
    nameZh: "广州塔",
    nameEn: "Canton Tower",
    citySlug: "guangzhou",
    category: "district",
    tags: ["Night View", "Photo", "Must-see"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/guangzhou-canton-tower/1200/800",
    gallery: ["https://picsum.photos/seed/guangzhou-canton-tower-gallery/1200/800"],
    summaryEn: "The twisted 600-metre TV tower dominating the Pearl River skyline — best viewed lit up at night.",
    summaryZh: "珠江畔扭腰造型的 600 米高电视塔，入夜后灯光绚烂，是广州的城市名片。",
    descriptionEn: "Take the metro to Zhujiang New Town across the river for the classic skyline photo, then cross the bridge for a river cruise.",
    descriptionZh: "可乘地铁到对岸珠江新城拍经典机位，再过桥登船夜游珠江。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 5600,
    postCount: 0,
    rating: 4.5,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "xi-an-xi-an-city-wall",
    nameZh: "西安城墙",
    nameEn: "Xi'an City Wall",
    citySlug: "xi-an",
    category: "history",
    tags: ["Must-see", "Photo", "Hiking"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/xi-an-xi-an-city-wall/1200/800",
    gallery: ["https://picsum.photos/seed/xi-an-xi-an-city-wall-gallery/1200/800"],
    summaryEn: "The best-preserved ancient city wall in China — cycle the full 14 km circuit above the old town.",
    summaryZh: "中国保存最完整的古城墙，全长约 14 公里，可骑行环游。",
    descriptionEn: "Rent a bike at the South Gate and ride the entire loop in about two hours, looking down over the old city.",
    descriptionZh: "在南门租一辆单车，两小时左右即可骑完一圈，俯瞰整座古城。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 5900,
    postCount: 0,
    rating: 4.6,
    featured: false,
    hiddenGem: false,
  },
  {
    slug: "chongqing-hongya-cave",
    nameZh: "洪崖洞",
    nameEn: "Hongya Cave",
    citySlug: "chongqing",
    category: "district",
    tags: ["Night View", "Food", "Photo"],
    level: null,
    addressEn: "",
    addressZh: "",
    lat: 0,
    lng: 0,
    coverImage: "https://picsum.photos/seed/chongqing-hongya-cave/1200/800",
    gallery: ["https://picsum.photos/seed/chongqing-hongya-cave-gallery/1200/800"],
    summaryEn: "A cliff-side complex of stilted traditional buildings that glows like a floating lantern city at night.",
    summaryZh: "依山而建的吊脚楼群，入夜灯火如悬空的宫崎骏世界，是重庆最上镜的夜景。",
    descriptionEn: "View it from the riverside road below for the full effect, then ride the nearby Liziba monorail that passes through a residential tower.",
    descriptionZh: "最佳机位在江岸步道仰拍；随后可乘穿楼而过的李子坝轻轨。",
    openingHours: "",
    ticketInfo: "",
    visitDuration: "",
    viewCount: 5200,
    postCount: 0,
    rating: 4.4,
    featured: false,
    hiddenGem: false,
  },
];

export const RELATED_POSTS_MOCK: RelatedPost[] = [
  { id: "p1", title: "48 hours around West Lake", slug: "48-hours-around-west-lake" },
  { id: "p2", title: "Where to eat in Hangzhou", slug: "where-to-eat-in-hangzhou" },
];
