/**
 * 景点模块 mock 数据（P0–P3 前端 mock 驱动）。
 *
 * <p>数据刻意双语、含复合 slug，并包含两处 "West Lake"（杭州/福州）以验证重名消歧。
 * P4（api-spots）接入真实后端后，本文件由爬虫种子数据取代。
 */
import type { City, Spot, RelatedPost } from "./types";

export const CITIES_MOCK: City[] = [
  {
    slug: "hangzhou",
    nameZh: "杭州",
    name: "Hangzhou",
    coverImage: "https://picsum.photos/seed/hangzhou/800/600",
    description: "West Lake, ancient temples and slow tea-house living.",
    bestSeason: "Mar–May",
    spotCount: 1,
  },
  {
    slug: "chengdu",
    nameZh: "成都",
    name: "Chengdu",
    coverImage: "https://picsum.photos/seed/chengdu/800/600",
    description: "Pandas, peppery hotpot and laid-back street life.",
    bestSeason: "Sep–Nov",
    spotCount: 2,
  },
  {
    slug: "xian",
    nameZh: "西安",
    name: "Xi'an",
    coverImage: "https://picsum.photos/seed/xian/800/600",
    description: "Terracotta warriors and the starting point of the Silk Road.",
    bestSeason: "Mar–May",
    spotCount: 1,
  },
  {
    slug: "guilin",
    nameZh: "桂林",
    name: "Guilin",
    coverImage: "https://picsum.photos/seed/guilin/800/600",
    description: "Karst peaks reflected in the dreamy Li River.",
    bestSeason: "Apr–Oct",
    spotCount: 1,
  },
  {
    slug: "suzhou",
    nameZh: "苏州",
    name: "Suzhou",
    coverImage: "https://picsum.photos/seed/suzhou/800/600",
    description: "Classical gardens and canal-side Ming architecture.",
    bestSeason: "Mar–May",
    spotCount: 1,
  },
  {
    slug: "lijiang",
    nameZh: "丽江",
    name: "Lijiang",
    coverImage: "https://picsum.photos/seed/lijiang/800/600",
    description: "Naxi old town beneath the Jade Dragon Snow Mountain.",
    bestSeason: "Apr–Jun",
    spotCount: 1,
  },
  {
    slug: "dunhuang",
    nameZh: "敦煌",
    name: "Dunhuang",
    coverImage: "https://picsum.photos/seed/dunhuang/800/600",
    description: "Silk Road oasis of desert grottoes and singing sands.",
    bestSeason: "May–Oct",
    spotCount: 1,
  },
  {
    slug: "zhangjiajie",
    nameZh: "张家界",
    name: "Zhangjiajie",
    coverImage: "https://picsum.photos/seed/zhangjiajie/800/600",
    description: "Pillared sandstone peaks rising through the clouds.",
    bestSeason: "Apr–Oct",
    spotCount: 1,
  },
];

export const SPOTS_MOCK: Spot[] = [
  {
    slug: "hangzhou-west-lake",
    nameZh: "西湖",
    nameEn: "West Lake",
    citySlug: "hangzhou",
    category: "nature",
    tags: ["UNESCO", "Free", "Photo"],
    level: "5A",
    addressEn: "West Lake Scenic Area, Hangzhou",
    addressZh: "杭州市西湖风景名胜区",
    lat: 30.2592,
    lng: 120.149,
    coverImage: "https://picsum.photos/seed/hangzhou-west-lake/800/600",
    gallery: [],
    summaryEn: "A calm lake ringed by willows, causeways and pagodas.",
    summaryZh: "垂柳、长堤与宝塔环抱的静谧湖泊。",
    descriptionEn: "Hangzhou's West Lake is the city's timeless heart.",
    descriptionZh: "西湖是杭州永恒的城市之心。",
    openingHours: "24h",
    ticketInfo: "Free",
    visitDuration: "Half day",
    viewCount: 9820,
    postCount: 31,
    rating: 4.7,
    featured: true,
    hiddenGem: true,
  },
  {
    slug: "fuzhou-west-lake",
    nameZh: "西湖",
    nameEn: "West Lake",
    citySlug: "fuzhou",
    category: "nature",
    tags: ["Free", "Local"],
    level: null,
    addressEn: "West Lake Park, Fuzhou",
    addressZh: "福州市西湖公园",
    lat: 26.1086,
    lng: 119.295,
    coverImage: "https://picsum.photos/seed/fuzhou-west-lake/800/600",
    gallery: [],
    summaryEn: "A smaller, quieter civic lake beloved by locals.",
    summaryZh: "更小、更安静、深受本地人喜爱的小西湖。",
    descriptionEn: "Fuzhou's West Lake is a neighborhood retreat.",
    descriptionZh: "福州西湖是街坊邻里的休憩之地。",
    openingHours: "06:00–22:00",
    ticketInfo: "Free",
    visitDuration: "2 hours",
    viewCount: 3120,
    postCount: 6,
    rating: 4.3,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "chengdu-kuanzhai-alley",
    nameZh: "宽窄巷子",
    nameEn: "Kuanzhai Alley",
    citySlug: "chengdu",
    category: "district",
    tags: ["Food", "Nightlife"],
    level: null,
    addressEn: "Kuanzhai Alley, Chengdu",
    addressZh: "成都市宽窄巷子",
    lat: 30.6703,
    lng: 104.056,
    coverImage: "https://picsum.photos/seed/chengdu-kuanzhai-alley/800/600",
    gallery: [],
    summaryEn: "Qing-dynasty lanes turned into food and teahouse strolls.",
    summaryZh: "清代巷道变身的美食与茶馆漫步区。",
    descriptionEn: "Kuanzhai Alley preserves Chengdu's courtyard charm.",
    descriptionZh: "宽窄巷子保留了成都的院落风情。",
    openingHours: "All day",
    ticketInfo: "Free",
    visitDuration: "2–3 hours",
    viewCount: 7640,
    postCount: 18,
    rating: 4.4,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "chengdu-panda-base",
    nameZh: "成都大熊猫繁育研究基地",
    nameEn: "Chengdu Panda Base",
    citySlug: "chengdu",
    category: "nature",
    tags: ["Wildlife", "Family"],
    level: "4A",
    addressEn: "Chengdu Research Base of Giant Panda Breeding",
    addressZh: "成都大熊猫繁育研究基地",
    lat: 30.7333,
    lng: 104.145,
    coverImage: "https://picsum.photos/seed/chengdu-panda-base/800/600",
    gallery: [],
    summaryEn: "See giant pandas up close in a bamboo forest sanctuary.",
    summaryZh: "在竹林秘境里近距离看大熊猫。",
    descriptionEn: "The Panda Base is the easiest place to meet giant pandas.",
    descriptionZh: "熊猫基地是近距离接触大熊猫最方便的地方。",
    openingHours: "07:30–18:00",
    ticketInfo: "¥55",
    visitDuration: "Half day",
    viewCount: 11200,
    postCount: 24,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "xian-terracotta",
    nameZh: "秦始皇兵马俑",
    nameEn: "Terracotta Army",
    citySlug: "xian",
    category: "history",
    tags: ["UNESCO", "Must-see"],
    level: "5A",
    addressEn: "Terracotta Army Museum, Xi'an",
    addressZh: "西安市秦始皇兵马俑博物馆",
    lat: 34.3853,
    lng: 109.2734,
    coverImage: "https://picsum.photos/seed/xian-terracotta/800/600",
    gallery: [],
    summaryEn: "Thousands of life-sized warriors guarding an emperor's tomb.",
    summaryZh: "守护帝王陵寝的成千上万陶制勇士。",
    descriptionEn: "The Terracotta Army is one of the world's great archaeological finds.",
    descriptionZh: "兵马俑是世界重大考古发现之一。",
    openingHours: "08:30–17:00",
    ticketInfo: "¥120",
    visitDuration: "Half day",
    viewCount: 13400,
    postCount: 29,
    rating: 4.9,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "guilin-lijiang-river",
    nameZh: "漓江",
    nameEn: "Li River",
    citySlug: "guilin",
    category: "nature",
    tags: ["UNESCO", "Photo", "Cruise"],
    level: "5A",
    addressEn: "Li River, Guilin",
    addressZh: "桂林市漓江",
    lat: 25.2736,
    lng: 110.299,
    coverImage: "https://picsum.photos/seed/guilin-lijiang/800/600",
    gallery: [],
    summaryEn: "A cruise through karst peaks that defined Chinese landscape art.",
    summaryZh: "穿行喀斯特峰林间的漂流，中国山水画的原型。",
    descriptionEn: "A Li River cruise from Guilin to Yangshuo is iconic.",
    descriptionZh: "桂林至阳朔的漓江漂流是经典路线。",
    openingHours: "Daytime cruises",
    ticketInfo: "From ¥210",
    visitDuration: "Full day",
    viewCount: 8760,
    postCount: 16,
    rating: 4.6,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "suzhou-humble-administrator",
    nameZh: "拙政园",
    nameEn: "Humble Administrator's Garden",
    citySlug: "suzhou",
    category: "culture",
    tags: ["UNESCO", "Garden"],
    level: "5A",
    addressEn: "Humble Administrator's Garden, Suzhou",
    addressZh: "苏州市拙政园",
    lat: 31.325,
    lng: 120.624,
    coverImage: "https://picsum.photos/seed/suzhou-humble/800/600",
    gallery: [],
    summaryEn: "The finest of Suzhou's classical scholar gardens.",
    summaryZh: "苏州古典文人园林的巅峰之作。",
    descriptionEn: "The Humble Administrator's Garden is a masterpiece of Ming garden design.",
    descriptionZh: "拙政园是明代园林设计的杰作。",
    openingHours: "07:30–17:30",
    ticketInfo: "¥70",
    visitDuration: "2–3 hours",
    viewCount: 6540,
    postCount: 11,
    rating: null,
    featured: true,
    hiddenGem: false,
  },
  {
    slug: "lijiang-old-town",
    nameZh: "丽江古城",
    nameEn: "Lijiang Old Town",
    citySlug: "lijiang",
    category: "culture",
    tags: ["UNESCO", "Walking"],
    level: "5A",
    addressEn: "Lijiang Old Town, Yunnan",
    addressZh: "云南省丽江古城",
    lat: 26.8721,
    lng: 100.2299,
    coverImage: "https://picsum.photos/seed/lijiang-old-town/800/600",
    gallery: [],
    summaryEn: "Car-free Naxi lanes of wood, water and snow-mountain views.",
    summaryZh: "无车的纳西族木构街巷，映着雪山。",
    descriptionEn: "Lijiang Old Town is a rare car-free medieval town.",
    descriptionZh: "丽江古城是罕见的免机动车中世纪古城。",
    openingHours: "All day",
    ticketInfo: "Free (maintenance fee may apply)",
    visitDuration: "Half day",
    viewCount: 5420,
    postCount: 9,
    rating: 4.5,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "dunhuang-mogao-caves",
    nameZh: "莫高窟",
    nameEn: "Mogao Caves",
    citySlug: "dunhuang",
    category: "history",
    tags: ["UNESCO", "Buddhist art"],
    level: "5A",
    addressEn: "Mogao Caves, Dunhuang",
    addressZh: "敦煌市莫高窟",
    lat: 40.0353,
    lng: 94.8097,
    coverImage: "https://picsum.photos/seed/dunhuang-mogao/800/600",
    gallery: [],
    summaryEn: "A thousand-year gallery of Buddhist cave art on the Silk Road.",
    summaryZh: "丝路上的千年佛教石窟艺术长廊。",
    descriptionEn: "The Mogao Caves hold the world's richest collection of Buddhist art.",
    descriptionZh: "莫高窟拥有世界上最丰富的佛教艺术收藏。",
    openingHours: "09:00–17:30",
    ticketInfo: "¥238 (booking required)",
    visitDuration: "Half day",
    viewCount: 4980,
    postCount: 8,
    rating: 4.7,
    featured: false,
    hiddenGem: true,
  },
  {
    slug: "zhangjiajie-national-forest",
    nameZh: "张家界国家森林公园",
    nameEn: "Zhangjiajie National Forest Park",
    citySlug: "zhangjiajie",
    category: "nature",
    tags: ["UNESCO", "Hiking", "Avatar"],
    level: "5A",
    addressEn: "Zhangjiajie National Forest Park, Hunan",
    addressZh: "张家界国家森林公园",
    lat: 29.317,
    lng: 110.43,
    coverImage: "https://picsum.photos/seed/zhangjiajie-forest/800/600",
    gallery: [],
    summaryEn: "Sandstone pillars that inspired the floating mountains of Avatar.",
    summaryZh: "启发《阿凡达》悬浮山的砂岩峰林。",
    descriptionEn: "Zhangjiajie's quartz-sandstone pillars rise hundreds of meters.",
    descriptionZh: "张家界的石英砂岩峰柱拔地数百米。",
    openingHours: "07:00–18:00",
    ticketInfo: "¥225 (4-day pass)",
    visitDuration: "1–2 days",
    viewCount: 9320,
    postCount: 14,
    rating: 4.8,
    featured: true,
    hiddenGem: false,
  },
];

export const RELATED_POSTS_MOCK: RelatedPost[] = [
  { id: "p1", title: "48 hours around West Lake", slug: "48-hours-around-west-lake" },
  { id: "p2", title: "Where to eat in Hangzhou", slug: "where-to-eat-in-hangzhou" },
];
