/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 帖子详情
         * @description 仅返回 PUBLISHED；草稿 / 已软删返回 404。
         */
        get: operations["get"];
        /**
         * 编辑帖子
         * @description 仅作者本人可编辑；可补丁式更新，含 DRAFT→PUBLISHED 发布。
         */
        put: operations["update"];
        post?: never;
        /**
         * 删除帖子（软删除）
         * @description 仅作者本人可删；软删除保留行，自动从所有列表 / 详情消失。
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公开列表
         * @description 仅返回 PUBLISHED；支持 sort=latest（cursor 翻页）/ top / most_commented（offset 翻页），每项含作者展示信息与互动统计。
         */
        get: operations["list"];
        put?: never;
        /**
         * 创建帖子
         * @description authorId 取自令牌主体；status 缺省 DRAFT，可直传 PUBLISHED 发布。
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 投票（创建 / 切换 / 取消）
         * @description 需鉴权。同类型再投取消，异类型切换。按用户维度限流。
         */
        post: operations["vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 顶层评论列表
         * @description 需鉴权；按创建时间倒序分页，含 reply_count 与作者信息。
         */
        get: operations["list_1"];
        put?: never;
        /**
         * 发布评论
         * @description 需鉴权。顶层评论 parent_comment_id 留空；回复须为本帖某顶层评论 id。
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}/bookmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 收藏状态查询
         * @description 需鉴权。精确返回当前用户是否已收藏该帖；帖子不存在返回 404。
         */
        get: operations["status"];
        put?: never;
        /**
         * 切换收藏
         * @description 需鉴权。已收藏则取消，未收藏则收藏。
         */
        post: operations["toggle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码（免鉴权）
         * @description 凭邮件中的一次性重置码设置新密码。
         *     重置成功会把未验证邮箱一并置为 ACTIVE，并使密码变更前签发的令牌全部失效。
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重发验证邮件（免鉴权）
         * @description 恒定返回 202：无论邮箱是否存在或是否已验证，均返回同一结果，不泄露账号存在性。
         *     仅当邮箱存在且状态为 EMAIL_UNVERIFIED 时才实际投递邮件。
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册
         * @description 以 EMAIL_UNVERIFIED 状态创建用户，**不签发任何令牌**，需先完成邮箱验证方可登录。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 access token
         * @description 以 refresh token 换取新签发的 access / refresh 令牌。
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description JWT 无状态，服务端不维护令牌黑名单；客户端须丢弃本地 access / refresh 令牌。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 按用户**当前**状态返回精确响应码：
         *     ACTIVE→200、LOCKED→423、DELETED→401、EMAIL_UNVERIFIED→403。
         *     邮箱不存在与密码错误共用 401 INVALID_CREDENTIALS，以收窄账号枚举面。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 申请密码重置（免鉴权）
         * @description 恒定返回 202：无论邮箱是否存在、是否已注销都返回同一结果，不泄露账号存在性。
         *     仅当邮箱存在且状态非 DELETED 时才实际投递重置邮件。
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{postId}/vote/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 投票统计
         * @description 需鉴权。返回 UP/DOWN 总数与当前用户投票态。
         */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的帖子
         * @description 需鉴权，返回当前用户全部状态（含 DRAFT）的帖子，并带互动统计与排序 / 分页。
         */
        get: operations["listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 返回固定文案，用于确认后端进程存活。
         */
        get: operations["hello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 回复列表
         * @description 需鉴权；按创建时间升序分页。
         */
        get: operations["replies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的收藏列表
         * @description 需鉴权；全量返回（失效帖子以 available=false 占位），按收藏时间倒序。
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 邮箱验证（免鉴权）
         * @description 凭邮件链接中的一次性验证码激活账号，**无需登录**。
         *     这是破解「登录返回 403 但验证邮件需登录态」死锁的关键端点。
         */
        get: operations["verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户信息
         * @description 返回当前登录用户信息，同时用于校验本地令牌是否仍有效。
         *     反映用户**当前**状态而非仅令牌签名有效性——登录后被锁定或注销会即时生效。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        /**
         * 注销账号（软删除）
         * @description 执行软删除：用户行保留，状态置为 DELETED 并写入 deletedAt。
         *     邮箱不可重新注册；已有业务数据（攻略、评论等）不物理删除。
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除评论（软删除）
         * @description 需鉴权且须为作者本人；顶层评论级联软删其回复。
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdatePostRequest: {
            title?: string;
            content?: string;
            coverImageUrl?: string;
            tags?: string[];
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
        };
        PostResponse: {
            request_id?: string;
            /** Format: uuid */
            id?: string;
            title?: string;
            content?: string;
            cover_image_url?: string;
            tags?: string[];
            status?: string;
            /** Format: uuid */
            author_id?: string;
            author_name?: string;
            author_avatar_url?: string;
            summary?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CreatePostRequest: {
            title: string;
            content: string;
            coverImageUrl?: string;
            tags?: string[];
            /** @enum {string} */
            status?: "DRAFT" | "PUBLISHED";
        };
        VoteRequest: {
            /** @enum {string} */
            vote_type: "UP" | "DOWN";
        };
        VoteResponse: {
            request_id?: string;
            /** Format: uuid */
            post_id?: string;
            user_vote?: string;
        };
        CreateCommentRequest: {
            content: string;
            /** Format: uuid */
            parent_comment_id?: string;
        };
        CommentResponse: {
            request_id?: string;
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            post_id?: string;
            /** Format: uuid */
            user_id?: string;
            /** Format: uuid */
            parent_comment_id?: string;
            content?: string;
            author_name?: string;
            author_avatar_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: int64 */
            reply_count?: number;
        };
        BookmarkResponse: {
            request_id?: string;
            /** Format: uuid */
            post_id?: string;
            bookmarked?: boolean;
        };
        ResetPasswordRequest: {
            code: string;
            newPassword: string;
        };
        ResendVerificationRequest: {
            email: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        UserResponse: {
            request_id?: string;
            /** Format: uuid */
            id?: string;
            email?: string;
            display_name?: string;
            avatar_url?: string;
            status?: string;
            /** Format: date-time */
            created_at?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthTokenResponse: {
            request_id?: string;
            access_token?: string;
            refresh_token?: string;
            user?: components["schemas"]["UserResponse"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
        PostListResponse: {
            request_id?: string;
            items?: components["schemas"]["PostSummary"][];
            next_cursor?: string;
            has_more?: boolean;
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        PostSummary: {
            request_id?: string;
            /** Format: uuid */
            id?: string;
            title?: string;
            cover_image_url?: string;
            tags?: string[];
            status?: string;
            /** Format: uuid */
            author_id?: string;
            author_name?: string;
            author_avatar_url?: string;
            summary?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: int64 */
            comment_count?: number;
            /** Format: int64 */
            up_vote_count?: number;
            /** Format: int64 */
            bookmark_count?: number;
        };
        VoteStatsResponse: {
            request_id?: string;
            /** Format: uuid */
            post_id?: string;
            /** Format: int64 */
            up_count?: number;
            /** Format: int64 */
            down_count?: number;
            user_vote?: string;
        };
        PageCommentResponse: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["CommentResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        BookmarkStatusResponse: {
            request_id?: string;
            /** Format: uuid */
            post_id?: string;
            bookmarked?: boolean;
        };
        BookmarkSummary: {
            /** Format: uuid */
            post_id?: string;
            available?: boolean;
            post?: components["schemas"]["PostSummary"];
        };
        PageBookmarkSummary: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["BookmarkSummary"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            /** Format: int32 */
            numberOfElements?: number;
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                sort?: string;
                cursor?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCommentResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkStatusResponse"];
                };
            };
        };
    };
    toggle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookmarkResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description 重置成功；重置码用后即焚，failedAttempts 归零 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_RESET_CODE（无效 / 已过期 / 已使用，三态同码）或 VALIDATION_FAILED（密码不在 8–72 字符） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：重置尝试过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description 已受理（恒定成功，不透露邮箱是否已注册） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED：邮箱格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：重发过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功，响应体 user.status 为 EMAIL_UNVERIFIED 且不含任何令牌 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description VALIDATION_FAILED：邮箱格式非法或密码不在 8–72 字符区间 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description EMAIL_ALREADY_REGISTERED：邮箱已注册（含已注销账号，邮箱不可复用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description RATE_LIMITED：同一 IP 注册过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已签发新的 access / refresh 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description TOKEN_INVALIDATED（令牌早于密码变更）/ ACCOUNT_DELETED（账号已注销） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHENTICATED：未携带有效令牌 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，签发 access / refresh 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description INVALID_CREDENTIALS（邮箱不存在或密码错误）/ ACCOUNT_DELETED（账号已注销） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED：邮箱未验证，前端须提供重发验证邮件的出路 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定，响应含 retryAfterSeconds */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description RATE_LIMITED：登录尝试过于频繁（IP 与 IP+email 双维度计数） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description 已受理（恒定成功，响应体为固定文案） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED：邮箱格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：申请过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoteStatsResponse"];
                };
            };
        };
    };
    listMine: {
        parameters: {
            query?: {
                sort?: string;
                cursor?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListResponse"];
                };
            };
        };
    };
    hello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    replies: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCommentResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageBookmarkSummary"];
                };
            };
        };
    };
    verify: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验证成功，用户状态转为 ACTIVE，验证码用后即焚 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description INVALID_VERIFICATION_CODE：验证码无效 / 已过期 / 已使用（三态同码，不泄露具体原因） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回当前用户信息（不含任何凭证类字段） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description UNAUTHENTICATED / ACCOUNT_DELETED / TOKEN_INVALIDATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 注销成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHENTICATED：未携带有效令牌 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
