/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重置密码（免鉴权）
         * @description 凭邮件中的一次性重置码设置新密码。
         *     重置成功会把未验证邮箱一并置为 ACTIVE，并使密码变更前签发的令牌全部失效。
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重发验证邮件（免鉴权）
         * @description 恒定返回 202：无论邮箱是否存在或是否已验证，均返回同一结果，不泄露账号存在性。
         *     仅当邮箱存在且状态为 EMAIL_UNVERIFIED 时才实际投递邮件。
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 注册
         * @description 以 EMAIL_UNVERIFIED 状态创建用户，**不签发任何令牌**，需先完成邮箱验证方可登录。
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新 access token
         * @description 以 refresh token 换取新签发的 access / refresh 令牌。
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description JWT 无状态，服务端不维护令牌黑名单；客户端须丢弃本地 access / refresh 令牌。
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 按用户**当前**状态返回精确响应码：
         *     ACTIVE→200、LOCKED→423、DELETED→401、EMAIL_UNVERIFIED→403。
         *     邮箱不存在与密码错误共用 401 INVALID_CREDENTIALS，以收窄账号枚举面。
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 申请密码重置（免鉴权）
         * @description 恒定返回 202：无论邮箱是否存在、是否已注销都返回同一结果，不泄露账号存在性。
         *     仅当邮箱存在且状态非 DELETED 时才实际投递重置邮件。
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 返回固定文案，用于确认后端进程存活。
         */
        get: operations["hello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 邮箱验证（免鉴权）
         * @description 凭邮件链接中的一次性验证码激活账号，**无需登录**。
         *     这是破解「登录返回 403 但验证邮件需登录态」死锁的关键端点。
         */
        get: operations["verify"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前用户信息
         * @description 返回当前登录用户信息，同时用于校验本地令牌是否仍有效。
         *     反映用户**当前**状态而非仅令牌签名有效性——登录后被锁定或注销会即时生效。
         */
        get: operations["me"];
        put?: never;
        post?: never;
        /**
         * 注销账号（软删除）
         * @description 执行软删除：用户行保留，状态置为 DELETED 并写入 deletedAt。
         *     邮箱不可重新注册；已有业务数据（攻略、评论等）不物理删除。
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ResetPasswordRequest: {
            code: string;
            newPassword: string;
        };
        ResendVerificationRequest: {
            email: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        UserResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
            avatarUrl?: string;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        AuthTokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            user?: components["schemas"]["UserResponse"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ForgotPasswordRequest: {
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description 重置成功；重置码用后即焚，failedAttempts 归零 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description INVALID_RESET_CODE（无效 / 已过期 / 已使用，三态同码）或 VALIDATION_FAILED（密码不在 8–72 字符） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：重置尝试过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description 已受理（恒定成功，不透露邮箱是否已注册） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED：邮箱格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：重发过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功，响应体 user.status 为 EMAIL_UNVERIFIED 且不含任何令牌 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description VALIDATION_FAILED：邮箱格式非法或密码不在 8–72 字符区间 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description EMAIL_ALREADY_REGISTERED：邮箱已注册（含已注销账号，邮箱不可复用） */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description RATE_LIMITED：同一 IP 注册过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 已签发新的 access / refresh 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description TOKEN_INVALIDATED（令牌早于密码变更）/ ACCOUNT_DELETED（账号已注销） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登出成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHENTICATED：未携带有效令牌 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功，签发 access / refresh 令牌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description INVALID_CREDENTIALS（邮箱不存在或密码错误）/ ACCOUNT_DELETED（账号已注销） */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description EMAIL_NOT_VERIFIED：邮箱未验证，前端须提供重发验证邮件的出路 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定，响应含 retryAfterSeconds */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description RATE_LIMITED：登录尝试过于频繁（IP 与 IP+email 双维度计数） */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description 已受理（恒定成功，响应体为固定文案） */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED：邮箱格式非法 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RATE_LIMITED：申请过于频繁 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    verify: {
        parameters: {
            query: {
                code: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 验证成功，用户状态转为 ACTIVE，验证码用后即焚 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description INVALID_VERIFICATION_CODE：验证码无效 / 已过期 / 已使用（三态同码，不泄露具体原因） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 返回当前用户信息（不含任何凭证类字段） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description UNAUTHENTICATED / ACCOUNT_DELETED / TOKEN_INVALIDATED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 注销成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description UNAUTHENTICATED：未携带有效令牌 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ACCOUNT_LOCKED：账号已锁定 */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
